services:

  nginx: 
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - cloud-1

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cloud-1

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WP_URL: $WP_URL
      WP_TITLE: $WP_TITLE
      WP_ADMIN_USER: $WP_ADMIN_USER
      WP_ADMIN_PASSWORD: $WP_ADMIN_PASSWORD
      WP_ADMIN_EMAIL: $WP_ADMIN_EMAIL
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - cloud-1

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    networks:
      - cloud-1

volumes:
  db_data:
  wordpress_data:

networks:
  cloud-1:
    driver: bridge