- import_playbook: docker.yml
- name: Application deployment...
  hosts: gcp
  become: true

  collections:
    - ansible.posix
  vars:
    project_src: "{{ playbook_dir }}/../../"
    project_dest: /opt/cloud-1

  tasks:

    - name: install rsync for files deployment
      apt:
        name: rsync
        update_cache: yes
  
    - name: make project directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ project_dest }}"
        - "{{ project_dest }}/volumes"
        - "{{ project_dest }}/volumes/wordpress"
        - "{{ project_dest }}/volumes/mariadb"

    - name: deploy files on hosts
      ansible.posix.synchronize:
        src: "{{ project_src }}/"
        dest: "{{ project_dest }}/"
        delete: no
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=README.md"
          - "--exclude=ansible/"

    - name: build and run containers
      ansible.builtin.command:
        argv:
          - docker
          - compose
          - up
          - "-d"
          - "--build"
      args:
        chdir: "{{ project_dest }}"
- import_playbook: wordpress.yml