- import_playbook: docker.yml
- name: Deploy Project on virtual machine
  hosts: gcp
  become: true

  vars:
    project_src: "{{ playbook_dir }}/../../"
    project_dest: /opt/cloud-1

  tasks:
    - name: Make project directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ project_dest }}"
        - "{{ project_dest }}/volumes"
        - "{{ project_dest }}/volumes/wordpress"
        - "{{ project_dest }}/volumes/mariadb"

    - name: Copy project
      ansible.builtin.copy:
        src: "{{ project_src }}/"
        dest: "{{ project_dest }}/"

    - name: Build and run containers
      ansible.builtin.command:
        argv:
          - docker
          - compose
          - up
          - "-d"
          - "--build"
      args:
        chdir: "{{ project_dest }}"
# - import_playbook: wp_install.yml
