- name: Start containers
  hosts: gcp
  become: true

  vars:
    project_dest: /opt/cloud-1

  tasks:
    - name: build and run containers
      ansible.builtin.command:
        argv:
          - docker
          - compose
          - up
          - "-d"
          - "--build"
      args:
        chdir: "{{ project_dest }}"