- name: Stop containers
  hosts: gcp
  become: true

  vars:
    project_dest: /opt/cloud-1

  tasks:
    - name: stop containers and unmount volumes
      ansible.builtin.command:
        argv:
          - docker
          - compose
          - down
          - "-v"
      args:
        chdir: "{{ project_dest }}"